### ISSUE TITLE
EP-4: Atlas Authentication

### ISSUE THREAD

**Issue by Wincenttjoi** [NUS-Fintech-Society/SD_Fintech_Website#30]
- [ ] Add UI on top navbar for admin to login
- [ ] Add authentication service using GCP through google account
- [ ] Add all nusfintech emails as admin to the authentication service

Refer to:
https://cloud.google.com/docs/authentication
